### ISSUE TITLE
Alert when user goes 'back' that their answers will be lost

### ISSUE THREAD

**Issue by knod** [codeforboston/docassemble-juvenilesealing#66]
When they press back, I believe their answers on that previous screen are destroyed, as are the answers on their current screen.

**Comment by knod** [comment]
Maybe not part of the MVP, but very painful.

**Comment by knod** [comment]
Can offer them the option of a review screen at the end to fix things they want to change.

**Comment by niharikasingh** [comment]
Duplicate of https://github.com/codeforboston/docassemble-juvenilesealing/issues/118
