### ISSUE TITLE
Refactor text content? **DECISION:** Keep text in the file with relevant logic.

### ISSUE THREAD

**Issue by knod** [codeforboston/docassemble-juvenilesealing#93]
There's a lot of it, and some of it is shared, so should it get separated from logic? Should the stuff related to specific interviews be mixed in with its logic while shared content is separated.

Goals:
- Make code more clear
- Make translation easier

**Comment by knod** [comment]
I'm not sure it will make code more clear, but it might make translation easier for sure.

**Comment by knod** [comment]
**DECISION:** Keep text in the file with relevant logic.

1. It's too much in one file.
2. It removes too much context.
3. Downloading stuff for translation isn't so bad.

**Comment by berit** [comment]
Closing this. If we encounter problems when actually doing the translations we can address those things then.
